[project]
name = "ganache-parse"
authors = ["Dio Cynthia <dio@example.com>"]
description = "Decentralized blockchain node performance monitoring and rewards platform"
telemetry = false
requirements = []
[contracts.governance]
path = "contracts/governance.clar"
depends_on = []

[contracts.data-validator]
path = "contracts/data-validator.clar"
depends_on = []

[contracts.node-manager]
path = "contracts/node-manager.clar"
depends_on = []

[contracts.metric-tracker]
path = "contracts/metric-tracker.clar"
depends_on = []

[contracts.reward-allocator]
path = "contracts/reward-allocator.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
